name: kazumi
description: "A new Flutter project."
publish_to: "none"

version: 1.9.6+10906

environment:
  # TV 适配：调整为 Flutter 3.38.9 内置的 Dart SDK 版本 (3.10.8)
  # 原先是 ">=3.3.4 <4.0.0"，修改为 >=3.10.0
  sdk: '>=3.10.0 <4.0.0'
  flutter: 3.38.9

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # TV 适配新增：遥控器焦点导航
  dpad: ^1.2.2
  focus_detector: ^2.0.1
  hive_ce: ^2.16.0

  # 原有依赖保持不变
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  dio: ^5.0.0
  connectivity_plus: ^6.0.5

  path_provider: ^2.1.5

  cached_network_image: ^3.4.1
  card_settings_ui: ^2.0.1

  flutter_volume_controller: ^1.3.2
  audio_video_progress_bar: ^2.0.2
  dynamic_color: ^1.8.1
  provider: ^6.1.2
  flutter_displaymode: ^0.6.0

  url_launcher: ^6.3.0
  window_manager: ^0.5.1
  xpath_selector: ^3.0.2
  xpath_selector_html_parser: ^3.0.1
  webview_flutter: ^4.13.1
  canvas_danmaku: ^0.3.1
  webdav_client: ^1.2.2
  tray_manager: ^0.5.0
  dlna_dart: ^0.0.8
  logger: ^2.6.2
  flutter_rating_bar: ^4.0.1
  scrollview_observer: ^1.22.0
  saver_gallery: ^4.1.0
  screen_brightness_android: ^2.1.3
  screen_brightness_ios: ^2.1.2
  screen_brightness_platform_interface: ^2.1.0
  synchronized: any
  flutter_svg: ^2.2.3
  antlr4: ^4.13.2
  fl_chart: ^1.1.1
  skeletonizer: ^2.1.2
  flutter_inappwebview_platform_interface: ^1.3.0+1
  flutter_inappwebview_ios: ^1.1.2
  flutter_inappwebview_macos: ^1.1.2
  flutter_inappwebview_android: ^1.1.3
  upgrader: ^12.3.0
  open_filex: ^4.7.0
  html: any
  material_color_utilities: any
  path: any
  
  webview_windows:
    git:
      url: https://github.com/Predidit/flutter-webview-windows.git 
      ref: 9962cb9416f867d9ce9f409ccd6784e78c5f72ca
  desktop_webview_window:
    git:
      url: https://github.com/Predidit/linux_webview_window.git 
      ref: 5a07358
  media_kit:
    git:
      url: https://github.com/Predidit/media-kit.git 
      ref: c04ddeead9ab468a3b5ddab0ee3789c77635841e
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git 
      ref: c04ddeead9ab468a3b5ddab0ee3789c77635841e
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git 
      ref: c04ddeead9ab468a3b5ddab0ee3789c77635841e
      path: ./libs/universal/media_kit_libs_video

dependency_overrides:
  media_kit_libs_linux:
    git:
      url: https://github.com/Predidit/media-kit.git 
      ref: c04ddeead9ab468a3b5ddab0ee3789c77635841e
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Predidit/media-kit.git 
      ref: c04ddeead9ab468a3b5ddab0ee3789c77635841e
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/Predidit/media-kit.git 
      ref: c04ddeead9ab468a3b5ddab0ee3789c77635841e
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Predidit/media-kit.git 
      ref: c04ddeead9ab468a3b5ddab0ee3789c77635841e
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Predidit/media-kit.git 
      ref: c04ddeead9ab468a3b5ddab0ee3789c77635841e
      path: ./libs/macos/media_kit_libs_macos_video

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  mobx_codegen: ^2.7.5
  hive_ce_generator: ^1.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3
  msix: ^3.16.12

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo/logo_android.png
  image_path_android: assets/images/logo/logo_android.png
  image_path_ios: assets/images/logo/logo_ios.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo/logo_android.png
  adaptive_icon_monochrome: assets/images/logo/logo_android.png
  macos:
    generate: true
    image_path: assets/images/logo/logo_rounded.png
  windows:
    generate: true
    image_path: assets/images/logo/logo_rounded.png
    icon_size: 256

flutter_native_splash:
  android: false
  ios: true
  web: false
  color_ios: "#ffffff"
  color_dark_ios: "#212121"
  image_ios: assets/images/logo/logo_ios.png
  image_dark_ios: assets/images/logo/logo_ios.png

msix_config:
  display_name: Kazumi
  publisher: CN=SignPath Foundation, O=SignPath Foundation, L=Lewes, S=Delaware, C=US
  logo_path: assets/images/logo/logo_rounded.png
  sign_msix: false
  install_certificate: false
  build_windows: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/plugins/
    - assets/shaders/
    - assets/images/logo/
    - assets/statements/

  fonts:
    - family: MI_Sans_Regular
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf
